import { useEffect, useState } from 'react';
import { createClient, type Session } from '@supabase/supabase-js';
import { ShieldCheck, LogIn, LogOut } from 'lucide-react';

const SUPABASE_URL = 'https://vttwfnnfcoavdhzeiqwl.supabase.co';
const SUPABASE_KEY = 'sb_publishable_ewRqbdjRDJM8wmz-qdaPBA_tvj72lwK6';
const supabase = createClient(SUPABASE_URL, SUPABASE_KEY, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true } });
const languages = { es: 'Español', pt: 'Português', en: 'English' } as const;
type Lang = keyof typeof languages;
const copy = {
  es:{login:'Iniciar sesión',register:'Registrarse',email:'Correo electrónico',password:'Contraseña',enter:'Entrar',create:'Crear cuenta',verifyEmail:'Revisa tu correo para confirmar la cuenta.',two:'Verificación en dos pasos',enable:'Activar 2FA',disable:'Desactivar 2FA',scan:'Escanea el QR con tu app autenticadora y escribe el código de 6 dígitos.',verify:'Verificar',account:'Mi cuenta',logout:'Cerrar sesión',language:'Idioma',code:'Código de 6 dígitos'},
  pt:{login:'Entrar',register:'Criar conta',email:'E-mail',password:'Senha',enter:'Entrar',create:'Criar conta',verifyEmail:'Verifique seu e-mail para confirmar a conta.',two:'Verificação em duas etapas',enable:'Ativar 2FA',disable:'Desativar 2FA',scan:'Escaneie o QR no seu app autenticador e digite o código de 6 dígitos.',verify:'Verificar',account:'Minha conta',logout:'Sair',language:'Idioma',code:'Código de 6 dígitos'},
  en:{login:'Sign in',register:'Register',email:'Email',password:'Password',enter:'Sign in',create:'Create account',verifyEmail:'Check your email to confirm the account.',two:'Two-step verification',enable:'Enable 2FA',disable:'Disable 2FA',scan:'Scan the QR with your authenticator app and enter the 6-digit code.',verify:'Verify',account:'My account',logout:'Sign out',language:'Language',code:'6-digit code'},
};

export default function AuthBar() {
  const [session,setSession]=useState<Session|null>(null); const [open,setOpen]=useState(false); const [register,setRegister]=useState(false); const [challenge,setChallenge]=useState<{factorId:string;challengeId:string}|null>(null); const [status,setStatus]=useState('');
  const [lang,setLang]=useState<Lang>((localStorage.getItem('bitey-language') as Lang)||'es'); const t=copy[lang];
  useEffect(()=>{ document.documentElement.lang=lang; localStorage.setItem('bitey-language',lang); },[lang]);
  useEffect(()=>{ void supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>data.subscription.unsubscribe(); },[]);
  useEffect(()=>{ if(session?.access_token){ const original=window.fetch; window.fetch=(input,init={})=>{const url=typeof input==='string'?input:input instanceof Request?input.url:input.toString(); if(url.includes('jobia-api.onrender.com')) init={...init,headers:{...(init.headers||{}),Authorization:`Bearer ${session.access_token}`}}; return original(input,init)}; return()=>{window.fetch=original}; } },[session]);
  const signIn=async()=>{setStatus('…');const email=(document.getElementById('jobia-auth-email') as HTMLInputElement)?.value.trim();const password=(document.getElementById('jobia-auth-password') as HTMLInputElement)?.value;const r=register?await supabase.auth.signUp({email,password,options:{emailRedirectTo:location.origin,data:{language:lang,product:'jobia'}}}):await supabase.auth.signInWithPassword({email,password});if(r.error){setStatus(r.error.message);return}if(register&&!r.data.session){setStatus(t.verifyEmail);return}if(r.data.session&&!register){const f=await supabase.auth.mfa.listFactors();const v=f.data?.totp?.find(x=>x.status==='verified');if(v){const c=await supabase.auth.mfa.challenge({factorId:v.id});if(c.data)setChallenge({factorId:v.id,challengeId:c.data.id});}}setSession(r.data.session);setStatus('');};
  const verify=async()=>{const code=(document.getElementById('jobia-auth-code') as HTMLInputElement)?.value.trim();if(!challenge)return;const r=await supabase.auth.mfa.verify({factorId:challenge.factorId,challengeId:challenge.challengeId,code});if(r.error){setStatus(r.error.message);return}setSession(r.data.session);setChallenge(null);setOpen(false);};
  return <div className="authbar"><select value={lang} aria-label={t.language} onChange={e=>setLang(e.target.value as Lang)}><option value="es">🌐 Español</option><option value="pt">🌐 Português</option><option value="en">🌐 English</option></select>{session?<><button className="auth-account" onClick={()=>setOpen(true)}><ShieldCheck size={16}/>{t.account}</button><button className="auth-icon" aria-label={t.logout} onClick={()=>void supabase.auth.signOut()}><LogOut size={17}/></button></>:<button className="auth-primary" onClick={()=>{setRegister(false);setOpen(true)}}><LogIn size={16}/>{t.login}</button>}{open&&<div className="auth-overlay" onClick={()=>setOpen(false)}><section className="auth-modal" onClick={e=>e.stopPropagation()}><button className="auth-x" onClick={()=>setOpen(false)}>×</button>{challenge?<><h2>{t.two}</h2><p>{t.code}</p><input id="jobia-auth-code" inputMode="numeric" maxLength={6} autoComplete="one-time-code"/><button className="auth-primary full" onClick={()=>void verify()}>{t.verify}</button></>:session?<AccountPanel t={t} onStatus={setStatus}/>:<><h2>{register?t.register:t.login}</h2><label>{t.email}<input id="jobia-auth-email" type="email" autoComplete="email"/></label><label>{t.password}<input id="jobia-auth-password" type="password" autoComplete={register?'new-password':'current-password'} minLength={6}/></label><button className="auth-primary full" onClick={()=>void signIn()}>{register?t.create:t.enter}</button><button className="auth-link" onClick={()=>setRegister(v=>!v)}>{register?t.login:t.register}</button></>}{status&&<p className="auth-status">{status}</p>}</section></div>}</div>;
}

function AccountPanel({t,onStatus}:{t:typeof copy.es;onStatus:(s:string)=>void}){const [qr,setQr]=useState('');const [factorId,setFactorId]=useState('');const [code,setCode]=useState('');const [enabled,setEnabled]=useState(false);useEffect(()=>{void supabase.auth.mfa.listFactors().then(({data})=>setEnabled(Boolean(data?.totp?.some(f=>f.status==='verified'))));},[]);const setup=async()=>{const r=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:'JobIA'});if(r.error){onStatus(r.error.message);return}setQr(r.data.totp.qr_code);setFactorId(r.data.id)};const verifySetup=async()=>{const c=await supabase.auth.mfa.challenge({factorId});if(c.error){onStatus(c.error.message);return}const r=await supabase.auth.mfa.verify({factorId,challengeId:c.data.id,code});if(r.error){onStatus(r.error.message);return}setEnabled(true);setQr('');onStatus('2FA activo.');};const disable=async()=>{const r=await supabase.auth.mfa.listFactors();const f=r.data?.totp?.find(x=>x.status==='verified');if(f){const z=await supabase.auth.mfa.unenroll({factorId:f.id});if(z.error)onStatus(z.error.message);else setEnabled(false);}};return <><h2>{t.account}</h2><p><b>{t.two}</b></p>{enabled?<button className="auth-link" onClick={()=>void disable()}>{t.disable}</button>:qr?<><p>{t.scan}</p><img className="auth-qr" src={qr} alt="TOTP QR"/><input value={code} onChange={e=>setCode(e.target.value)} inputMode="numeric" maxLength={6}/><button className="auth-primary full" onClick={()=>void verifySetup()}>{t.verify}</button></>:<button className="auth-primary full" onClick={()=>void setup()}>{t.enable}</button>}</>}
